<template>
  <text :style="{'font-family':type,'color':color,'font-size':size}"><slot>{{iconName}}</slot></text>
</template>

<style scoped>
  
</style>

<script>
  const domModule = weex.requireModule('dom');
  export default {
    props: {
      name: {
        type: String,
        default: ''
      },
      type: {
        type: String,
        default: 'fontcategory'
      },
      size: {
        type: Number,
        default: 40
      },
      color: {
        type: String,
        default: 'red'
      }
    },
    beforeCreate:function(){
      domModule.addRule('fontFace', {
          'fontFamily': 'fontcategory',
          'src': "url('http://h5.sumslack.com/font-wx/category2.ttf?r=101')"
      });
      domModule.addRule('fontFace', {
          'fontFamily': 'fontsumslack',
          'src': "url('http://h5.sumslack.com/font-wx/fontsumslack.ttf?r=101')"
      });
    },
    computed:{
      iconName(){
        let _iconText = "";
        if(this.name!=""){
          if(this.type == "fontcategory"){
            _iconText = this.iconItems[this.name];
          }else{
            _iconText = this.iconData[this.name];
          }
          console.log("icontext:",_iconText)
        }
        return _iconText;
      }
    },
    data: function () {
        return {
            icon:"",
            iconItems: {
                "icon-diaoyu": "\ue603",
                "icon-jiuba":"\ue609",
                "icon-zhoubianyou":"\ue627",
                "icon-yumaoqiu": "\ue652",
                "icon-huisuo": "\ue608",
                "icon-qiu": "\ue604",
                "icon-caizhai": "\ue63f",
                "icon-ktv": "\ue65a",
                "icon-icon6": "\ue655", //跑步
                "icon-meirong": "\ue825",
                "icon-qiugan": "\ue629",
                "icon-yuqie": "\ue66e",
                "icon-mishitaotuo": "\ue63e",
                "icon-ktv1": "\ue659",

                "icon-jiuba1": "\ue6cc",
                "icon-shaokao": "\ue6ed",
                "icon-zuyu": "\ue6f3",
                "icon-wenquan": "\ue6f5",
                "icon-tuangou": "\ue61c",
                "icon-gengduo": "\ue6a4",
                "icon-cycling": "\ue62a",

                "icon-wangqiu": "\ue671",
                "icon-jucan": "\ue6a8",
                "icon-nongjiale": "\ue846",
                "icon-zoulu-": "\ue689",
                "icon-bieshu": "\ue638",
                "icon-dianying": "\ue653",
                "icon-pashan": "\ue601",

                "icon-jianshen": "\ue5da",
                "icon-jianshen1": "\ue5dc",
                "icon-qipai": "\ue60b",
                "icon-yanchanghui": "\ue64f",
                "icon-jiuba2": "\ue61f",
                "icon-yule": "\ue615",
                "icon-lvyou": "\ue697",

                "icon-youyong": "\ue60a",
                "icon-danshenpaidui": "\ue60c",
                "icon-jucan1": "\ue620",
                "icon-huwai": "\ue636",
                "icon-shunfengche": "\ue69a",
                "icon-pin": "\ue665",
                "icon-majiangwutianchong-": "\ue60f",

                "icon-zuqiu": "\ue60d",
                "icon-PingPong": "\ue619",
                "icon-zhuoyou": "\ue610"
            },
            iconData: {
                "icon-appreciate": "\ue644",
                "icon-appreciatefill": "\ue6e3",
                "icon-check": "\ue645",
                "icon-roundcheckfill": "\ue656",
                "icon-roundcheck": "\ue657",
                "icon-close": "\ue646",
                "icon-roundclosefill": "\ue658",
                "icon-roundclose": "\ue659",
                "icon-delete": "\ue6b4",
                "icon-deletefill": "\ue6a6",
                "icon-add": "\ue6da",
                "icon-roundadd": "\ue6d9",
                "icon-edit": "\ue649",
                "icon-emoji": "\ue64a",
                "icon-favorfill": "\ue64b",
                "icon-favor": "\ue64c",
                "icon-loadding": "\ue64f",
                "icon-locationfill": "\ue650",
                "icon-location": "\ue651",
                "icon-phone": "\ue652",
                "icon-roundrightfill": "\ue65a",
                "icon-roundright": "\ue65b",
                "icon-search": "\ue65c",
                "icon-searchlist": "\ue6fe",
                "icon-time": "\ue65f",
                "icon-timefill": "\ue65e",
                "icon-taxi": "\ue65d",
                "icon-unfold": "\ue661",
                "icon-fold": "\ue6de",
                "icon-warnfill": "\ue662",
                "icon-warn": "\ue663",
                "icon-camerafill": "\ue664",
                "icon-camera": "\ue665",
                "icon-commentfill": "\ue666",
                "icon-comment": "\ue667",
                "icon-likefill": "\ue668",
                "icon-like": "\ue669",
                "icon-notificationfill": "\ue66a",
                "icon-notification": "\ue66b",
                "icon-order": "\ue66c",
                "icon-samefill": "\ue66d",
                "icon-same": "\ue66e",
                "icon-deliver": "\ue671",
                "icon-evaluate": "\ue672",
                "icon-pay": "\ue673",
                "icon-send": "\ue675",
                "icon-shop": "\ue676",
                "icon-shopfill": "\ue697",
                "icon-ticket": "\ue677",
                "icon-left": "\ue679",
                "icon-right": "\ue6a3",
                "icon-cascades": "\ue67c",
                "icon-discover": "\ue67e",
                "icon-discoverfill": "\ue6ba",
                "icon-list": "\ue682",
                "icon-more": "\ue684",
                "icon-moreandroid": "\ue6a5",
                "icon-myfill": "\ue685",
                "icon-my": "\ue686",
                "icon-scan": "\ue689",
                "icon-settings": "\ue68a",
                "icon-questionfill": "\ue690",
                "icon-question": "\ue691",
                "icon-form": "\ue699",
                "icon-pic": "\ue69b",
                "icon-picfill": "\ue72c",
                "icon-filter": "\ue69c",
                "icon-footprint": "\ue69d",
                "icon-top": "\ue69e",
                "icon-down": "\ue703",
                "icon-pulldown": "\ue69f",
                "icon-pullup": "\ue6a0",
                "icon-refresh": "\ue6a4",
                "icon-refund": "\ue6ac",
                "icon-cart": "\ue6af",
                "icon-cartfill": "\ue6b9",
                "icon-qrcode": "\ue6b0",
                "icon-remind": "\ue6b2",
                "icon-profile": "\ue6b7",
                "icon-profilefill": "\ue77a",
                "icon-homefill": "\ue6bb",
                "icon-home": "\ue6b8",
                "icon-messagefill": "\ue779",
                "icon-message": "\ue6bc",
                "icon-addressbook": "\ue6bd",
                "icon-link": "\ue6bf",
                "icon-lock": "\ue6c0",
                "icon-unlock": "\ue6c2",
                "icon-vip": "\ue6c3",
                "icon-vipcard": "\ue6ee",
                "icon-activity": "\ue6c5",
                "icon-activityfill": "\ue775",
                "icon-friendaddfill": "\ue6c9",
                "icon-friendadd": "\ue6ca",
                "icon-friendfamous": "\ue6cb",
                "icon-friend": "\ue6cc",
                "icon-friendfill": "\ue726",
                "icon-goods": "\ue6cd",
                "icon-goodsfill": "\ue778",
                "icon-selection": "\ue6ce",
                "icon-selectionfill": "\ue6e1",
                "icon-explore": "\ue6d2",
                "icon-explorefill": "\ue6dd",
                "icon-present": "\ue6d3",
                "icon-presentfill": "\ue732",
                "icon-squarecheckfill": "\ue6d4",
                "icon-square": "\ue6d5",
                "icon-squarecheck": "\ue6d6",
                "icon-round": "\ue6d7",
                "icon-roundfill": "\ue6d8",
                "icon-notificationforbidfill": "\ue6db",
                "icon-game": "\ue6df",
                "icon-redpacket": "\ue6e0",
                "icon-similar": "\ue6e2",
                "icon-infofill": "\ue6e4",
                "icon-info": "\ue6e5",
                "icon-forwardfill": "\ue6ea",
                "icon-forward": "\ue6eb",
                "icon-rechargefill": "\ue6ec",
                "icon-recharge": "\ue6ed",
                "icon-voice": "\ue6ef",
                "icon-voicefill": "\ue6f0",
                "icon-friendfavor": "\ue6f1",
                "icon-wifi": "\ue6f2",
                "icon-share": "\ue6f3",
                "icon-wefill": "\ue6f4",
                "icon-we": "\ue6f5",
                "icon-lightauto": "\ue6f6",
                "icon-lightforbid": "\ue6f7",
                "icon-lightfill": "\ue6f8",
                "icon-light": "\ue6fa",
                "icon-camerarotate": "\ue6f9",
                "icon-barcode": "\ue6fb",
                "icon-flashlightclose": "\ue6fc",
                "icon-flashlightopen": "\ue6fd",
                "icon-service": "\ue6ff",
                "icon-servicefill": "\ue737",
                "icon-sort": "\ue700",
                "icon-mobile": "\ue704",
                "icon-mobilefill": "\ue705",
                "icon-copy": "\ue706",
                "icon-countdownfill": "\ue707",
                "icon-countdown": "\ue708",
                "icon-noticefill": "\ue709",
                "icon-notice": "\ue70a",
                "icon-upstagefill": "\ue70e",
                "icon-upstage": "\ue70f",
                "icon-choicenessfill": "\ue714",
                "icon-choiceness": "\ue715",
                "icon-clothesfill": "\ue716",
                "icon-clothes": "\ue717",
                "icon-creativefill": "\ue718",
                "icon-creative": "\ue719",
                "icon-female": "\ue71a",
                "icon-male": "\ue71c",
                "icon-keyboard": "\ue71b",
                "icon-pullleft": "\ue71f",
                "icon-pullright": "\ue720",
                "icon-rankfill": "\ue721",
                "icon-rank": "\ue722",
                "icon-bad": "\ue723",
                "icon-cameraadd": "\ue724",
                "icon-cameraaddfill": "\ue727",
                "icon-focus": "\ue725",
                "icon-apps": "\ue729",
                "icon-paintfill": "\ue72a",
                "icon-paint": "\ue72b",
                "icon-refresharrow": "\ue72d",
                "icon-markfill": "\ue730",
                "icon-mark": "\ue731",
                "icon-repeal": "\ue733",
                "icon-album": "\ue734",
                "icon-peoplefill": "\ue735",
                "icon-people": "\ue736",
                "icon-repair": "\ue738",
                "icon-repairfill": "\ue73a",
                "icon-file": "\ue739",
                "icon-taoxiaopu": "\ue73b",
                "icon-attentionfill": "\ue73c",
                "icon-attention": "\ue73d",
                "icon-commandfill": "\ue73e",
                "icon-command": "\ue73f",
                "icon-communityfill": "\ue740",
                "icon-community": "\ue741",
                "icon-read": "\ue743",
                "icon-calendar": "\ue74a",
                "icon-cut": "\ue74b",
                "icon-magic": "\ue74c",
                "icon-backwardfill": "\ue74d",
                "icon-forwardfill1": "\ue74e",
                "icon-stop": "\ue750",
                "icon-tagfill": "\ue751",
                "icon-tag": "\ue752",
                "icon-group": "\ue753",
                "icon-move": "\ue754",
                "icon-all": "\ue755",
                "icon-backdelete": "\ue756",
                "icon-hotfill": "\ue757",
                "icon-hot": "\ue758",
                "icon-post": "\ue759",
                "icon-radiobox": "\ue75b",
                "icon-radioboxfill": "\ue763",
                "icon-rounddown": "\ue75c",
                "icon-upload": "\ue75d",
                "icon-videofill": "\ue75e",
                "icon-video": "\ue75f",
                "icon-writefill": "\ue760",
                "icon-write": "\ue761",
                "icon-punch": "\ue764",
                "icon-shake": "\ue765",
//                    "icon-add1": "\ue767",
//                    "icon-move1": "\ue768",
                "icon-safe": "\ue769",
                "icon-crownfill": "\ue776",
                "icon-crown": "\ue777",
                "icon-sound": "\ue77b",
                "icon-sponsorfill": "\ue77c",
                "icon-weunblock": "\ue780",
                "icon-weblock": "\ue77f",
                "icon-upblock": "\ue77e",
                "icon-sponsor": "\ue77d",
                "icon-babyfill": "\ue710",
                "icon-baby": "\ue711",
            }
        }
    }
  };
</script>